#!/bin/bash
# This spawns a 4GB centos 7.4 instance attached to public using SSH key file.
# Usage: ./bro-deploy [INSTANCE_NAME]

# Set the vars
VM_NAME=$1
HOST=$2
FLAVOR=a552bff9-ddb4-4043-9786-8043367f3921
PUBLIC_INTERFACE=b41a1d65-d339-40cf-b943-ef0b9ea547cb
RHEL_IMAGE=4b9c96cd-6780-420a-b3ae-286a84cb35d6
CENT_IMAGE=abf206f3-e26c-4e55-bfae-28e7f9732cb3
DATE=$(date +%F)
LOG=/tmp/${1}_build.bros-deploy.$DATE
KEYNAME=home_auth
RED="\033[0;31m"
GREEN="\033[1;32m"
NC="\033[0m"
YELLER="\033[1;33m"
BLUE="\033[1;34m"

# Ensures only 1 argument is assessed.
if [ "$#" -lt "1" ] || [ "$#" -gt "2" ]; then
	echo -e "${RED}Invalid argument count.${NC}"
	exit 1
fi
case $1 in
	--help|help|-h)
		echo -e "${GREEN}Usage: $0 VM_NAME${NC}"
		echo "For RHEL, use name like: rhel*|rhce*|web*|nfs*|network*|storage*|ssh*|iscsi*|samba*|smtp*|dns* "
		echo "For CENTOS, use name NOT like RHEL types. "
		echo "For target host, make host the 2nd argument."
		exit 0
		;;
esac

if [ -n "$HOST" ]; then
		HOST_PARAMS="--availability-zone nova:$HOST"
fi

# Use centos 7 as default.
case $VM_NAME in
	rhel*|rhce*|nfs*|network*|web*|storage*|ssh*|iscsi*|samba*|smtp*|dns*)
		echo -e "${GREEN}Red Hat Enterprise Linux build accepted...${NC}"
		OS=rhel
		source $HOME/.supernova_venv/bin/activate
		$HOME/.supernova_venv/bin/supernova bro boot --image $RHEL_IMAGE --flavor $FLAVOR \
			--nic net-id=$PUBLIC_INTERFACE --key $KEYNAME $HOST_PARAMS $VM_NAME > $LOG
		;;
	*)
		echo -e "${GREEN}CentOS build accepted...${NC}"
		OS=centos
		source $HOME/.supernova_venv/bin/activate
		$HOME/.supernova_venv/bin/supernova bro boot --image $CENT_IMAGE --flavor $FLAVOR \
			--nic net-id=$PUBLIC_INTERFACE --key $KEYNAME $HOST_PARAMS $VM_NAME > $LOG
		;;
esac

sleep 3
echo -e "${YELLER}Collect instance facts...${NC}"
# Sift out IP facts
RETRY_COUNT=0
INSTANCE_UUID=$(awk '/\| id/{print $4}' $LOG)
while [ -z "$INSTANCE_PUB_IP" ] && [ "$RETRY_COUNT" -lt 6 ]; 
do echo -e "${YELLER}Configuring public networking...Poll $RETRY_COUNT ${NC}"; sleep 3;
let RETRY_COUNT=$RETRY_COUNT+1
INSTANCE_PUB_IP=$(supernova bro show $INSTANCE_UUID |awk '/provider network/{print $5}')
done 

if [ -z "$INSTANCE_PUB_IP" ]; then
	echo -e "${RED}Instance failed to obtain IP.${NC}"
	exit 1
fi


# Set username for login. default rhel names have been changed in base image. Don't use cloud-user or centos.
case $OS in
	rhel)
		OS_LOGIN=root
		;;
	centos)
		OS_LOGIN=root
		;;
	*)
		OS_LOGIN=root
		;;
esac

# Progress and info section.
echo -e "${BLUE}---- instance obtained ip${NC} ${YELLER}$INSTANCE_PUB_IP${NC} ${BLUE}----${NC}"
echo -e "${BLUE}----       instance is booting.         ----${NC}"
sleep 5
echo -ne '####                     (15%$)\r'
sleep 5
echo -ne '#########                (30%)\r'
sleep 5
echo -ne '############             (40%)\r'
sleep 5
echo -ne '##############           (50%)\r'
sleep 5
echo -ne '##################       (60%)\r'
sleep 10
echo -ne '#####################    (85%)\r'
sleep 10
echo -ne '########################(100%)\r'
echo -ne '\n'

#echo -e "${YELLER}Cleaning up log $LOG${NC}"
#rm -f $LOG

# Auto login
# Times are longer for cent and fedora as they seem to lag.
case $OS in
        rhel*)
                echo -e "${GREEN}Logging into $INSTANCE_PUB_IP${NC} disabled"
#		sleep 20
#		ssh $OS_LOGIN@$INSTANCE_PUB_IP
                ;;
        centos*)
                echo -e "${GREEN}Logging into $INSTANCE_PUB_IP${NC} disabled"
#		sleep 15
#		ssh $OS_LOGIN@$INSTANCE_PUB_IP
                ;;
        *)
                echo "place_holder_catchall"
#		sleep 5
#		ssh $OS_LOGIN@$INSTANCE_PUB_IP
                ;;
esac

# Handling script exit status.
case $? in 
	0)
	exit 0
	;;
	*)
	echo -e "${RED}Disconnected${NC} $OS_LOGIN@$INSTANCE_PUB_IP"
	exit 1
	;;
esac
