#!/bin/bash
# This spawns a 2GB Fedora 22 instance attached to public and private networks using SSH key file.
# Usage: ./bro-deploy [INSTANCE_NAME]

# Set the vars
VM_NAME=$1
FLAVOR=2
PUBLIC_INTERFACE=f9455ea8-4687-466a-9962-388472d8f0d2
# No repo enabled:
#RHEL_IMAGE=388c42d3-f5c8-40a5-abcf-9a27ef3a5f9a
# RHEL install disk repo enabled:
RHEL_IMAGE=4b9c96cd-6780-420a-b3ae-286a84cb35d6
CENT_IMAGE=5f99db2f-f6c9-4e93-93ab-f97815976d17
DATE=$(date +%F)
LOG=$HOME/${1}_build.bros-deploy.$DATE

RED="\033[0;31m"
GREEN="\033[1;32m"
NC="\033[0m"
YELLER="\033[1;33m"
BLUE="\033[1;34m"

# Ensures only 1 argument is assessed.
if [ "$#" -ne "1" ]; then
	echo -e "${RED}Invalid argument.${NC} Script requires ${YELLER}only${NC} instance name."
	exit 1
fi

case $1 in
	--help|help|-h)
		echo -e "${GREEN}Usage: $0 VM_NAME${NC}"
		echo "For RHEL, use name like: rhel*|rhce*|web*|nfs*|network*|storage*|ssh*|iscsi*|samba*|smtp*|dns* "
		echo "For CENTOS, use name NOT like RHEL types. "
		exit 0
		;;
esac

# Use centos 7 as default.
case $VM_NAME in
	rhel*|rhce*|nfs*|network*|web*|storage*|ssh*|iscsi*|samba*|smtp*|dns*)
		echo -e "${GREEN}Red Hat Enterprise Linux build accepted...${NC}"
		OS=rhel
		source $HOME/.supernova_venv/bin/activate
		$HOME/.supernova_venv/bin/supernova bro boot --image $RHEL_IMAGE --flavor $FLAVOR --nic net-id=$PUBLIC_INTERFACE $VM_NAME > $LOG
		;;
	*)
		echo -e "${GREEN}CentOS build accepted...${NC}"
		OS=centos
		source $HOME/.supernova_venv/bin/activate
		$HOME/.supernova_venv/bin/supernova bro boot --image $CENT_IMAGE --flavor $FLAVOR --nic net-id=$PUBLIC_INTERFACE $VM_NAME > $LOG
		;;
esac

sleep 3
echo -e "${YELLER}Collect instance facts...${NC}"
# Sift out IP facts
RETRY_COUNT=0
INSTANCE_UUID=$(awk '/\| id/{print $4}' $LOG)
while [ -z "$INSTANCE_PUB_IP" ] && [ "$RETRY_COUNT" -lt 6 ]; 
do echo -e "${YELLER}Configuring public networking...Poll $RETRY_COUNT ${NC}"; sleep 3;
let RETRY_COUNT=$RETRY_COUNT+1
INSTANCE_PUB_IP=$(supernova bro show $INSTANCE_UUID |awk '/provider network/{print $5}')
done 

if [ -z "$INSTANCE_PUB_IP" ]; then
	echo -e "${RED}Instance failed to obtain IP.${NC}"
	exit 1
fi


# Set username for login. default rhel names have been changed in base image. Don't use cloud-user or centos.
case $OS in
	rhel)
		OS_LOGIN=root
		;;
	centos)
		OS_LOGIN=root
		;;
	*)
		OS_LOGIN=root
		;;
esac

# Progress and info section.
echo -e "${BLUE}---- instance obtained ip${NC} ${YELLER}$INSTANCE_PUB_IP${NC} ${BLUE}----${NC}"
echo -e "${BLUE}----       instance is booting.         ----${NC}"
sleep 5
echo -ne '####                     (15%$)\r'
sleep 5
echo -ne '#########                (30%)\r'
sleep 5
echo -ne '############             (40%)\r'
sleep 5
echo -ne '##############           (50%)\r'
sleep 5
echo -ne '##################       (60%)\r'
sleep 10
echo -ne '#####################    (85%)\r'
sleep 10
echo -ne '########################(100%)\r'

echo -ne '\n'
echo -e "${YELLER}Cleaning up log $LOG${NC}"
rm -f $LOG

# Auto login
# Times are longer for cent and fedora as they seem to lag.
case $OS in
        rhel*)
                echo -e "${GREEN}Logging into $INSTANCE_PUB_IP${NC}"
		sleep 15
		ssh $OS_LOGIN@$INSTANCE_PUB_IP
                ;;
        centos*)
                echo -e "${GREEN}Logging into $INSTANCE_PUB_IP${NC}"
		sleep 5
		ssh $OS_LOGIN@$INSTANCE_PUB_IP
                ;;
        *)
                echo "place_holder_catchall"
		sleep 5
		ssh $OS_LOGIN@$INSTANCE_PUB_IP
                ;;
esac

# Handling script exit status.
case $? in 
	0)
	exit 0
	;;
	*)
	echo -e "${RED}Disconnected${NC} $OS_LOGIN@$INSTANCE_PUB_IP"
	exit 1
	;;
esac
